### ISSUE TITLE
Shared Global State

### ISSUE THREAD

**Issue by lexstefan** [Atmos4/van-element#5]
Hello, searched documentation but i did not find a way to share state globally, meaning between two or more van-elements. Sorta like in an island architecture. Now, when it comes to island architecture, astro we can use nanostores. I'm curious to know if there is a **recommended way** / sollution for van-element. I mean i could use custom events, maybe pubSub to subscribe to events with data and that would be the easiest possible way, but those would work if both van-elements are present.

**Comment by Atmos4** [comment]
Hi! Thank you for your interest in the project.

1. The most straight forward way to share state between components is simply to put the state in a global-scoped `van.state`. If you need more complex state, you can even use [VanX.reactive](https://vanjs.org/x#reactive-object) to build a store. Things will work automatically because VanJS is awesome :)

Here is a simple example on CodePen: https://codepen.io/atmos4/pen/RNbozMV.

2. A more complex approach would be to use a context (think React Context), so that the state is only shared to a part of the DOM. This approach is slower in terms of performance and more complex to implement, and would make use of the WebComponent context specification.

I actually have some draft code for option 2. If you are interested I can polish it and make it into a small package. However I would always recommend option 1, as it is simpler, more performant and sufficient in most cases.

None of the information I gave here is available in the docs, so I will work on fixing that asap

**Comment by Atmos4** [comment]
I added shared state in the docs, under an "Advanced section". I feel like this is a topic that often deters people from using custom elements/web components so thank you for bringing it up.

Let me know if you would want me to publish a "Van Context" package too!

I am going to close the issue for now. Thank you for your feedback and interest!

**Comment by lexstefan** [comment]
Wow, thanks a lot. I appreciate it! 🥳 🎄 🎅
