### ISSUE TITLE
connectedCallback example

### ISSUE THREAD

**Issue by kangaroolab** [Atmos4/van-element#6]
hi, do you have working example how I can create some custom function for connectedCallback for a custom element?

thanks

**Comment by Atmos4** [comment]
The main `define` function runs in the `connectedCallback`. So any code you put there will execute when the component is already connected to the DOM.

However, the function is also a VanJS component, so that means that the VanJS code itself isn't constructed. For a rare edge case where you need to interact with connected VanJS inside the Van Element, there is the `mount`hook. You can find more info in the docs.

But the mount hook is not super useful and you will find you can do 99% of what you want inside `define`.

**Comment by Atmos4** [comment]
If you provide some code example or an idea of what you are trying to achieve, I might be able to answer in a more precise way.

**Comment by Atmos4** [comment]
I am going to close the issue for now, but feel free to reply with more info or questions if you want extra help @kangaroolab
